spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    #url: jdbc:mysql://localhost:3306/zwlpda-database?useUnicode=true&characterEncoding=utf8&useSSL=true&serverTimezone=UT
    #username: root
    #password: 1qaz2wsx
    url: ${AZURE_MYSQL_CONNECTIONSTRING}
    



mybatis:
  mapper-locations: classpath:mapping/**/*.xml
  type-aliases-package: com.example.springboot1.model
  configuration:
    map-underscore-to-camel-case: true
    use-generated-keys: true